// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gs4QPFa0lXzzOlOYEnoCWeHygG6B_zQ',
    appId: '1:531634102438:web:a3402047fbed45c2dc9467',
    messagingSenderId: '531634102438',
    projectId: 'reminder7222026',
    authDomain: 'reminder7222026.firebaseapp.com',
    storageBucket: 'reminder7222026.firebasestorage.app',
    measurementId: 'G-BSDKLMHPRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3F507g7m0H1urShBjt33XCFq8DWY7FQ',
    appId: '1:531634102438:android:b7801d719bc1f1cedc9467',
    messagingSenderId: '531634102438',
    projectId: 'reminder7222026',
    storageBucket: 'reminder7222026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8gs4QPFa0lXzzOlOYEnoCWeHygG6B_zQ',
    appId: '1:531634102438:web:dbc41589114bd4b0dc9467',
    messagingSenderId: '531634102438',
    projectId: 'reminder7222026',
    authDomain: 'reminder7222026.firebaseapp.com',
    storageBucket: 'reminder7222026.firebasestorage.app',
    measurementId: 'G-P1NZ5BJFKC',
  );
}
